# configures for Lorpheux by Legend Lee

# Settings
title: LorpheuX
author: Legend
email: legendlee1314@gmail.com
description: "LorpheuX -- Legend's Blog."
url: "http://legendlee1314.github.io"
baseurl: ""


# Optionals
animated: true
show_related_posts: false
show_post_footers: true
show_social_icons: true

# Build
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
paginate: 4
sass:
  compressed: true

# Self information
blog_name: LorpheuX
blog_description: Legend's Blog

# Social Links
github_username: legendlee1314
twitter_username: legendlee1314
disqus_shortname: lorpheux
stackoverflow_id:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Analytics
google_analytics: UA-38617326-1
baidu_tongji: 6ce79452dd7f61208b986b61b835536e
